[package]
name = "takoyaki_plugin_deployer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite = "*"
tokio = { version = "1.21.2", features = ["full"] }
futures-channel = "0.3.25"
futures-util = "0.3.25"
tungstenite = "0.17.3"
sha2 = "0.10.6"
base64 = "0.13.1"

