[package]
name = "takoyaki_plugin_deployer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.87"
serde = { version = "1.0", features = ["derive"] }
rocket = { version = "0.5.0-rc.2" , features = ["json"] }
rand = "0.8.4"
sha2 = "0.10.6"

[dependencies.uuid]
version = "1.2.1"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
]

