#[derive(Debug)]
pub enum Error {
    NoStartFunctionFound,
    NoExecuteFunctionFound,
    ConfigDirNotFound,
    CannotCreateDirectory,
    NoConfigFound,
    ReadError,
    BuggedConfig,
    StateUnset,
    InvalidHexColorCode,
    ReqwestError(reqwest::Error),
    SerializeJSONError(serde_json::Error),
    SerializeTOMLError(toml::de::Error),
    HexColorParseError(Option<colorsys::ParseError>),
    CacheNotCreated(std::io::Error),
    WriteError(std::io::Error),
    InvalidHexColorConfig(colorsys::ParseError),
}
